trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Building...'
  inputs:
    command: 'build'
    arguments: '--verbosity:quiet'
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*.csproj'
    arguments: '--collect "Code coverage"'
    workingDirectory: 'test'
- task: DotNetCoreCLI@2
  displayName: 'Publishing...'
  inputs:
    command: 'publish'
    arguments: '--output $(Build.ArtifactStagingDirectory) --verbosity:quiet'
    publishWebProjects: true
    zipAfterPublish: false
- task: PublishBuildArtifacts@1
  displayName: 'Copying artifacts...'
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'Binaries'
    publishLocation: Container