trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Building...'
  inputs:
    command: 'build'
    arguments: '--verbosity:quiet -maxcpucount'
- task: DotNetCoreCLI@2
  displayName: 'Testing...'
  inputs:
    command: 'test'
    projects: '**/*.csproj'
    arguments: '--verbosity:quiet'
    workingDirectory: 'test'
- task: DotNetCoreCLI@2
  displayName: 'Uploading new articles and checking getting their plagiarism score...'
  inputs:
    command: 'run'
    arguments: '--configuration Release'
    workingDirectory: 'src\utils\BlogApp.Utils.UploaderAndChecker'
- task: DotNetCoreCLI@2
  displayName: 'Preparing artifacts...'
  inputs:
    command: 'publish'
    arguments: '--output $(Build.ArtifactStagingDirectory)'
    publishWebProjects: true
    workingDirectory: 'src\gui\BlazorApp.Gui.Blazor'
    zipAfterPublish: false
- task: PublishBuildArtifacts@1
  displayName: 'Publishing artifacts...'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'Binaries'
    publishLocation: 'Container'
