trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Building...'
  inputs:
    command: 'build'
    arguments: '--verbosity:quiet -maxcpucount'
- task: DotNetCoreCLI@2
  displayName: 'Testing...'
  inputs:
    command: 'test'
    projects: '**/*.csproj'
    arguments: '--verbosity:quiet --collect "Code coverage"'
    workingDirectory: 'test'
- task: DotNetCoreCLI@2
  displayName: 'Checking for new articles...'
  inputs:
    command: 'run'
    workingDirectory: 'src\utils\BlogApp.Utils.NewArticleUploader'
- task: DotNetCoreCLI@2
  displayName: 'Publishing GUI...'
  inputs:
    command: 'publish'
    publishWebProjects: true
    workingDirectory: 'src\gui\BlazorApp.Gui.Blazor'
